version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # RabbitMQ management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Volume for persistent data

volumes:
  rabbitmq_data:


# without use the docker compose
# step 1 ) docker pull rabbitmq
# step 2 ) docker run -d --name rabbitmq-my -p 5672:5672 -p 15672:15672 rabbitmq
# step 3 ) docker exec -it rabbitmq rabbitmqctl status | grep 'RabbitMQ' //==> for get version of the rabbitMq
# step 4 ) docker exec -it rabbitmq rabbitmqctl stop





